pkg/cmd/info.go
=> Additional improvements

pkg/cmd/inspect.go, pkg/util/port_forward.go
Attempts to examine containers for any ports that may be set.
If a "metrics" port is set, it is used. Otherwise, defaults to 8443.
=> improve port-forwarding logic

pkg/cmd/inspect.go
This fixes namespace gathering.
/assign @juanvallejo
=> improve directory structure and gathering

cmd/must-gather.go, pkg/cmd/events.go, pkg/cmd/inspect/inspect.go, pkg/cmd/inspect/resource.go, pkg/cmd/inspect/util.go
=> restructure inspect to handle polymorphic resources

pkg/cmd/audit.go, pkg/cmd/inspect/resource.go, pkg/cmd/inspect/util.go
=> add groupName to dir structure

pkg/cmd/inspect/inspect.go, pkg/cmd/inspect/resource.go
~~few more tweaks needed, but almost good to merge.~~
cc @sferich888
=> allow more than one arg

pkg/cmd/inspect/inspect.go
Completes https://github.com/openshift/must-gather/pull/33 with minor changes
=> Creating a default input when --default is supplied

pkg/cmd/inspect/resource.go
=> use resource builder to gather all namespace data

pkg/cmd/inspect/inspect.go, pkg/cmd/inspect/inspect_test.go
cc @soltysh @deads2k @sferich888
=> begin adding unit tests for cmd/inspect

pkg/cmd/inspect/pod.go
Adds more detail to errors that may occur from collecting endpoint data from containers
=> add detail to container-data-gathering errors

OWNERS
=> remove juanvallejo from OWNERS files

pkg/cmd/certinspection/certinspection.go
I just had to debug why a connection couldn't trust the kube-apiserver.  This updates the inspect-cert to analyze ca.crt too.
/assign @soltysh
=> add introspection of ca.crt

pkg/cmd/inspect/resource.go, pkg/cmd/inspect/route.go, pkg/cmd/inspect/secret.go
This way we don't accidentally dump the sensitive data.
/assign @mfojtik
=> elide secret data from sensitive resources

Dockerfile, Dockerfile.rhel7, README.md, collection-scripts/OWNERS
This adds a spot for collection-scripts to be added and makes @sferich888 the owner.
/assign @sferich888
=> add collection-scripts to must-gather image

pkg/cmd/inspect/secret.go
some keys in secrets are known to hold public data, not private data and we use this public data to match signers to ca bundles.
@mfojtik @sferich888
=> restore secret keys which are known to be public

pkg/cmd/analyze-e2e/analyzers/pods_analyzer.go
Add restart counts to failed containers report.
=> analyze: add restart counts

collection-scripts/gather
Required gathering items/resources that support will need to start looking at a cluster.
=> Adding the first draft of the CEE Playlist 

collection-scripts/gather
I clearly forgot that storage classes were important.
=> getting the stroage classes for a cluster

collection-scripts/gather
cc: @RickJWagner please review.
=> volumes is not a resource and volumeattachemets are important so adding

pkg/cmd/inspect/util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1698687
/assign @sanchezl
=> Use full resource name (including group) when retrieving

pkg/cmd/audit/io.go
Fixes panic when the response status is nil (case when request not finished (timeout?)) otherwise this panics.
=> audit: fix case when response status is nil

pkg/cmd/audit/audit_filter.go, pkg/cmd/events/event_filter.go, pkg/cmd/events/events.go, pkg/cmd/events/io.go, pkg/cmd/events/sort.go, pkg/util/filtering.go
This allows matching on trailing stars, so I can look at `openshift-*` namespaces.
=> Filtering sorting

pkg/cmd/inspect/resource.go, pkg/cmd/inspect/util.go
=> Be explicit about related objects type

collection-scripts/gather
These are also cluster scoped and useful data describing the
state of the system.
=> gather: Collect machineconfigpools too

collection-scripts/gather
=> Bug 1715634: ensure we collect cluster version information

collection-scripts/gather, collection-scripts/gather_network_logs
https://jira.coreos.com/browse/SDN-428
=> Gather extended network data

pkg/util/filtering.go
fixes matching for negative users.
=> handle pure negation and don't match empty strings

pkg/cmd/inspect/pod.go
The filename for storing version information was incorrect.
/assign @sallyom
=> Bug 1722523: fix filenames for collecting versions and metrics

collection-scripts/gather_network_logs
https://bugzilla.redhat.com/show_bug.cgi?id=1726137
=> Bug 1726137: Fix BASE_COLLECTION_PATH on gather_network_logs

pkg/cmd/audit/audit.go, pkg/cmd/audit/audit_filter.go, pkg/cmd/audit/io.go
`--before=2019-07-19T11:50:00-04:00` now works.
=> filter audit log by time

pkg/cmd/inspect/namespace.go
@juanluisvaladas can you please review this. 
cc: @deads2k
=> Bug 1737558: Adding PVC's to Namespace resource collection

pkg/cmd/events/events.go
=> event supports only warning-only

Makefile
Signed-off-by: Avram Levitter <alevitte@redhat.com>
=> Fixed spelling in Makefile of gather

collection-scripts/gather
Catching up with openshift/api@700fd891c4 (openshift/api#470).
=> collection-scripts/gather: Add imagecontentsourcepolicies.operator.openshift.io

collection-scripts/gather_network_logs, must-gather.md
Also, copy the must-gather.md from enhancements.
It was deleted. This is the version before the delete.
sdn-851 - Add network must-gather support to step-registry
=> Improve network data capture

collection-scripts/gather_network_logs
This captures the ovn database files on each master node
It also includes the node name in the file name of the
log files.
Bug 1834836
https://bugzilla.redhat.com/show_bug.cgi?id=1834836
SDN-946 - gather_network_logs - also capture sbdb and nbdb
https://issues.redhat.com/browse/SDN-946
=> bug 1834836: gather_network_logs - capture sbdb and nbdb

collection-scripts/gather_network_ovn_trace
Scan through the generated trace for key lines in ovn bringup and report
them.
SDN-1028 - Trace: generate trace of networking bring up
Trace: generate trace of networking bring up
=> Extract trace of ovn bringup

collection-scripts/gather, collection-scripts/gather_audit_logs, collection-scripts/gather_core_dumps, collection-scripts/gather_etcd, collection-scripts/gather_network_logs, collection-scripts/gather_network_ovn_trace, collection-scripts/gather_service_logs, collection-scripts/gather_windows_node_logs, collection-scripts/openshift-must-gather
Proof in https://github.com/openshift/origin/pull/25493
=> Bug 1861746: force disk flush after collecting audit logs

collection-scripts/gather, collection-scripts/gather_admission_webhooks
=> adding collection script for validation and mutatin admission webhooks

collection-scripts/gather_core_dumps, collection-scripts/gather_network_logs
Backport `gather_core_dump` Functionality to OCP 4.5 for CI Runs that use the functionality, and also bring in port and flow dumping in `gather_network_logs`
=> Bug 1887446: [release-4.5]Backport `gather_core_dumps` 

collection-scripts/gather
=> Split resources to named and groups

collection-scripts/gather_network_logs
This PR adds some data collection that is specific to ovn-ipsec encrypted clusters
=> [SDN-1317] Add Data collection for ovn-ipsec encrypted clusters 

collection-scripts/gather, collection-scripts/gather_haproxy_config
Add script file collection-scripts/gather_haproxy_config to collect haproxy config files for each ingress controller in the cluster.
This is in support of https://issues.redhat.com/browse/NE-356.
=> NE-356: Add HAProxy config files to must-gather

collection-scripts/collect_service_logs, collection-scripts/gather_network_logs, collection-scripts/gather_service_logs, collection-scripts/gather_service_logs_util
We will remove the ovs pod, therefore we need must-gather to attach these logs in the sosreport.
/assign @squeed
=> Bug 1906655: Add openvswitch services to must-gather

collection-scripts/gather, collection-scripts/gather_monitoring
Add a script to collect alerts when running must-gather. 
/assign @openshift/openshift-team-monitoring
=> collect alerts from the cluster

collection-scripts/gather, collection-scripts/gather_priority_and_fairness
API Priority and Fairness exposes a set of debug endpoints (HTTP) that could help us troubleshoot p&f related issues.
Closes: BZ#1916392
=> Bug 1916392: Gather API priority and fairness debug endpoints

collection-scripts/gather_service_logs
- also alpha ordering of the services
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>
=> Bug 1907353: Add ovs related services to GENERAL_SERVICES

collection-scripts/gather_network_logs
Backporting gather_network_log changes to 4.6
=> Bug 1975970:  Backport gather network logs

collection-scripts/gather_audit_logs
Implementing https://github.com/openshift/enhancements/pull/792/files#diff-731ba465970a87a66f9744cfdd69a780f81235315e7ff6ea1232f7ef41ac7d7dR174.
=> audit: error out with audit profile None

collection-scripts/gather, collection-scripts/gather_insights
This should resolve https://github.com/openshift/must-gather/issues/255
cc: @iNecas
=> Adding automated insights archive collection

collection-scripts/gather_metallb_logs
MetalLB speaker component label was updated.
=> Update MetalLB speaker component label

collection-scripts/gather_network_logs
Added "[]" around possible ipv6 addresses to join with port
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> Bug 2052929:Fix ovn-nbctl commands for ipv6

collection-scripts/gather_network_logs
Add egressips and cloudprivateipconfigs collection as cluster-scoped resources
Add egressfirewalls and networkpolicies counters to gather_network_logs
These objects are required for networking debugging.
=> Bug 2023295: Add networking resources

collection-scripts/gather_multus_logs, collection-scripts/gather_network_logs
Script added that gathers multus logs from pods across nodes
Signed-off-by: nicklesimba <simha.nikhil@gmail.com>
=> Bug 2090730: Adds collection of Multus log files

collection-scripts/gather_sriov
Added improvments to the sriov gather script:
1. Use the SRIOV_NS var instead of static: "openshift-sriov-network-operator".
2. In the gather_ethtool function, do not log interfaces with @ in the name.
=> Bug 2091658: Improve the sriov gather script

collection-scripts/gather_network_logs
Backport of https://github.com/openshift/must-gather/pull/308
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> [release-4.8] Bug 2092264: Add networking resources

collection-scripts/gather_ingress_node_firewall
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
=> Add ingress node firewall must-gather collection script

collection-scripts/gather_windows_node_logs
This PR adds the Windows Instance Config Daemon (WICD) 
to the list of service log files collected from Windows nodes.
=> WINC-958: Collect WICD logs from Windows nodes

collection-scripts/gather_service_logs
This has come up a lot, we should have had this from the start.
=> Gather ostree related bits

collection-scripts/common.sh, collection-scripts/gather_ingress_node_firewall, collection-scripts/gather_metallb, collection-scripts/gather_network_observability, collection-scripts/gather_nmstate, collection-scripts/gather_sriov
This commit extracts the logic of fetching the operator ns into a util function in a new common.sh script, to reduce code duplication.
=> Create a generic "get_operator_ns" util function

collection-scripts/gather_network_logs
We are adding support for IC in 4.14. See
https://issues.redhat.com/browse/SDN-3733
for more details.
This commit ensures we have support for
gathering logs from both modes. We will remove
the legacy version in future a.k.a `gather_ovn_kubernetes_data_legacy_mode` will just be deleted
```
drwxr-xr-x 2 surya surya 9.5M Jul 17 18:03 ovnk_database_store
-rw-r--r-- 1 surya surya 1.6M Jul 17 18:03 ovnk_database_store.tar.gz
[surya@hidden-temple network_logs]$ cd ovnk_database_store/
[surya@hidden-temple ovnk_database_store]$ ls -ltrh
total 9.5M
-rw-r--r-- 1 surya surya 1.4M Jul 17 18:03 ovnkube-node-ssh2b_sbdb
-rw-r--r-- 1 surya surya 483K Jul 17 18:03 ovnkube-node-ssh2b_nbdb
-rw-r--r-- 1 surya surya 1.4M Jul 17 18:03 ovnkube-node-s4597_sbdb
-rw-r--r-- 1 surya surya 508K Jul 17 18:03 …
```
=> SDN-3687: Support gathering DBs for OVNK-Interconnect mode

collection-scripts/gather_sriov
gather_sriov: Fix typos and collect SRIOV cache at /var/lib/cni/sriov
=> gather_sriov: Fix typos and collect SRIOV cache at /var/lib/cni/sriov

collection-scripts/gather_windows_node_logs
This is a manual cherry-pick of https://github.com/openshift/must-gather/pull/374
=> OCPBUGS-24523: [release-4.12] Add csi-proxy logs collection in must-gather for Windows nodes

collection-scripts/gather
PR following the RFE request #407 
Added the resources in the `group_resources` array.
=> NO-JIRA: Adding the missing clusterresourcequota and Flowcontrol resources

README.md
README has a sentence that doesn't read correctly, this PR corrects it.
=> NO-JIRA: Correct typo.

Makefile
Followup to https://github.com/openshift/must-gather/pull/432
/assign @ashwindasr
=> NO-JIRA: Update dockerfile rename changes

OWNERS
/assign @ardaguclu @sferich888
=> NO-JIRA: Expand the approvers for must-gather

collection-scripts/gather_etcd
Collects the etcd object count in the `etcd_info` directory as `json` file.
=> RFE-5765: Collect etcd object count

.ci-operator.yaml, Dockerfile.ocp
=> OCPBUGS-45363: Update to use 4.19 image
