- pkg/cmd/info.go
- pkg/util/port_forward.go
- pkg/util/writer.go
Adds a port-forwarder and a PortForwardURLGetter to replace the RemoteExecutor.
This will allow endpoint data retrieval from pods without needing to
generate a token, create a custom namespace or serviceaccount.
TODO: remove RemoteExecutor pieces + related dependencies.
cc @deads2k
> add port-forwarded url request support

- pkg/cmd/inspect.go
- pkg/util/pod_readiness.go
cc @deads2k 
Removes the hardcoded namespace backup for clusteroperator resources.
Ensure pods have a Ready: true condition before proceeding to collect data
> Ensure pod readiness

- .gitignore
- Makefile
- README.md
- dev-helpers/cmd/dev-helpers.go
- pkg/cmd/events.go
- pkg/util/events.go
- vendor/github.com/xeonx/timeago/LICENSE
- vendor/github.com/xeonx/timeago/README.md
- vendor/github.com/xeonx/timeago/timeago.go
- vendor/github.com/xeonx/timeago/timeago_test.go
This will add second binary `./bin/openshift-dev-helpers` which will provide tools useful for OpenShift developer teams.
The first addition there is `events` command which will fetch the `events.json` file available in test artifacts and print its content in parsed, human-friendly form.
An example output of running:
`
$ ./bin/openshift-dev-helpers events https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-openshift-apiserver-operator/115/pull-ci-openshift-cluster-openshift-apiserver-operator-master-e2e-aws/510/artifacts/e2e-aws/events.json --component=openshift-cluster-kube-apiserver-operator
`
```bash
2 minutes   RoleCreated                           Created Rolerbac.authorization.k8s.io./prometheus-k8s -n openshift-kube-apiserver because it was missing
2 minutes …
```
> Add dev-helpers and 'events' parser

- pkg/cmd/inspect/inspect.go
- pkg/cmd/inspect/resource.go
Prevents config.openshift.io and operator.openshift.io data
collection, unless explicitly dealing with a clusteroperator resource
cc @sferich888 @deads2k
> limit config/operator.openshift.io data gathering

- pkg/cmd/events.go
- pkg/util/events.go
This allow to specify `-f` for events helper as google storage for test grid tests require auth and the URLs have ttl.
> add local file support for events

- pkg/cmd/inspect/inspect.go
Given a truly polymorphic, re-entrant helper, there isn't a  need for defaults to be set.  Instead of wiring something like this, users should just indicate all the things they want to collect.
/assign @juanvallejo @soltysh
> remove defaults since we have a truly polymorphic command

- cmd/openshift-dev-helpers/main.go
- pkg/cmd/certinspection/certinspection.go
I'm losing my mind debugging certs, so this allows `./openshift-dev-helpers inspect-certs --local -f '/home/deads/Downloads/decarr-01/openshift-kube-apiserver-configmaps'` or `./openshift-dev-helpers inspect-certs configmaps secrets` or `oc create secret generic --dry-run -oyaml kubelet --from-file=tls.crt=/home/deads/Downloads/kubelet-client-current.pem | ./openshift-dev-helpers inspect-certs --local -f -` to get output like:
```
$ ./openshift-dev-helpers inspect-certs --local -f '/home/deads/Downloads/decarr-01/openshift-kube-apiserver-configmaps'
"kube-ca" issuer="root-ca" (2019-02-06 14:47:20 +0000 UTC to 2029-02-03 14:47:20 +0000 UTC)
"kube-csr-signer_@1549465488" issuer="kube-csr-signer_@1549465488" (2019-02-06 15:04:48 +0000 UTC to 2019-02-06 19:04:49 +0000 UTC) …
```
> helper for inspecting cert resources

- .gitignore
- pkg/cmd/inspect/namespace.go
- pkg/cmd/inspect/pod.go
- pkg/cmd/inspect/resource.go
- pkg/cmd/inspect/util.go
This separates the namespace configs by group and makes the namespace detection go through the polymorphic path.
```
└── namespaces
├── openshift-config
│   ├── apps
│   │   ├── daemonsets.yaml
│   │   ├── deployments.yaml
│   │   ├── replicasets.yaml
│   │   └── statefulsets.yaml
│   ├── apps.openshift.io
│   │   └── deploymentconfigs.yaml
│   ├── autoscaling
│   │   └── horizontalpodautoscalers.yaml
│   ├── batch
│   │   ├── cronjobs.yaml
│   │   └── jobs.yaml
│   ├── build.openshift.io
│   │   ├── buildconfigs.yaml
│   │   └── builds.yaml
│   ├── core
│   │   ├── configmaps.yaml
│   │   ├── events.yaml
│   │   ├── pods.yaml
│   │   ├── replicationcontrollers.yaml
│   │   ├── secrets.yaml
│   │   └── services.yaml
│   ├── image.openshift.io
│   │   └── imagestreams.yaml
│   ├── …
```
> fix the namespace resource layout

- pkg/cmd/certinspection/certinspection.go
Let's us see SANs and groups:
```
secrets/initial-serving-cert[openshift-config] - tls (2019-02-22 13:59:00 +0000 UTC)
"system:kube-apiserver" [serving,client] groups=[kube-master] validFor=[172.30.0.1,127.0.0.1,api.ci-ln-q8f6ipk-703b0.origin-ci-int-aws.dev.rhcloud.com,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster.local,localhost] issuer="kube-ca" (2019-02-22 13:50:41 +0000 UTC to 2029-02-19 13:50:48 +0000 UTC)
"kube-ca" [] issuer="<self>" (2019-02-22 13:50:41 +0000 UTC to 2029-02-19 13:50:41 +0000 UTC)
```
/assign @soltysh
> dump group and serving info for certs

- cmd/openshift-dev-helpers/main.go
- pkg/cmd/analyze-e2e/analyze-e2e.go
- pkg/cmd/analyze-e2e/analyzers/clusteroperators_analyzer.go
- pkg/cmd/analyze-e2e/analyzers/pods_analyzer.go
- pkg/cmd/analyze-e2e/get_artifacts.go
Sample output: https://gist.githubusercontent.com/mfojtik/001f4fe94e6e49025b541ac3f863d519/raw/62fa1ddd673b58aec7db9267bee776f1ad6b601a/gistfile1.txt
Comes with handy `Analyzer` interface one can implement for other artifact files (events, secrets, configs, etc) to detect common problems.
@sttts @deads2k this will save you at least couple minutes every day :-)
> analyze-e2e: add openshift-dev only tool to help with e2e-aws artifacts analysis

- pkg/cmd/audit/audit.go
- pkg/cmd/audit/io.go
NOTE: This is super inefficient implementation of `dev-tools -o top`.
The full syntax is:
```
openshift-dev-helpers audit -f FILE -o top --by user
openshift-dev-helpers audit -f FILE -o top --by verb
```
First will display top 10 users making any request. Second will display top 5 requests per verb (GET, CREATE, etc.)
> audit: add top output type

- pkg/cmd/audit/audit.go
- pkg/cmd/audit/io.go
Sample:
```
❯ ./openshift-dev-helpers audit -f ~/xxx/audit -o top --by=resource
73425x               v1/secrets
24507x               v1/nodes
20497x               v1/configmaps
4729x                v1/pods
3378x                v1/persistentvolumes
3356x                v1/persistentvolumeclaims
2499x                authentication.k8s.io/v1beta1/tokenreviews
1599x                v1/serviceaccounts
1240x                v1/services
1120x                v1/events
955x                 v1/endpoints
817x                 network.openshift.io/v1/hostsubnets
813x                 network.openshift.io/v1/netnamespaces
752x                 apiregistration.k8s.io/v1/apiservices
731x                 network.openshift.io/v1/egressnetworkpolicies
692x …
```
> Add --by=resource output

- Dockerfile
- Dockerfile.rhel7
Change the base image used when running `make images` locally to better match what gets built during a release build.
> change must-gather image base FROM base to cli

- collection-scripts/gather
- collection-scripts/gather_audit_logs
- collection-scripts/gather_service_logs
This PR is dependant on https://github.com/openshift/must-gather/pull/82 so that our image has the tools it needs to collect node logs (audit and services).
> Adding audit and host service log collection with oc

- collection-scripts/gather
Reverts openshift/must-gather#96
This was merged without arhictect approval for an unapproved bug at an unapproved time. Do not do this again.
> Revert "Bug 1715634: ensure we collect cluster version information"

- collection-scripts/gather
Debugging issues with the cluster require access to etcd-member container logging. This PR adds `openshift-etcd` namespace to the resource list.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1722548
> Bug 1722548: collection-scripts/gather: add ns/openshift-etcd

- pkg/cmd/inspect/resource.go
- pkg/cmd/inspect/util.go
When empty `Name` and/or `Namespace` values are specified in a `ClusterOperator.spec.relatedObjects` gather everything that matches the non-empty field that are specified.
For example, the following entry in `ClusterOperator.spec.relatedObjects` would collect all `CatalogSources` in the `openshift-marketplace` namespace:
```
status:
relatedObjects:
- group:     operators.coreos.com
namespace: openshift-marketplace
resource:  catalogsources
```
https://bugzilla.redhat.com/show_bug.cgi?id=1720321
> Bug 1720321 - must-gather does not collect all non-core CRs in the given namespace

- pkg/cmd/inspect/secret.go
Redact the `kubectl.kubernetes.io/last-applied-configuration` in Secrets to avoid exposing non-public data Secrets after an `oc apply -f` update.
> Bug 1723472: must-gather should redact kubectl.kubernetes.io/last-applied-configuration in secrets

- collection-scripts/gather
Otherwise the command will exit with an error when running with ovn-kubernetes or any other network plugin. (eg, this breaks the test `[cli] oc adm must-gather runs successfully [Suite:openshift/conformance/parallel]` in e2e-aws-ovn-kubernetes)
The clusternetwork object is redundant if we have network.operators.openshift.io anyway. It would be nice to collect the hostsubnet objects if and only if they existed, but maybe that can be added later. (We're going to want to add some ovn-kubernetes-specific stuff for only when ovn-kubernetes is running as well.)
> Don't gather openshift-sdn-specific networking resources

- collection-scripts/gather
This is to supplement https://github.com/openshift/machine-api-operator/pull/391 
We should deprecate https://github.com/openshift/must-gather/pull/118 in favor of this PR.
> Fixing machine collection 

- collection-scripts/gather
- collection-scripts/version
Conform to must-gather spec: https://github.com/openshift/enhancements/blame/master/must-gather.md#L113
Sample output:
```
openshift/must-gather
4.2-2019-09-19-151434
```
If the version can't be determined from the image id, the entire image id is provided instead.
> generate /must-gather/version file

- collection-scripts/gather_network_logs
This commit ensures that all Kuryr related data
is gathered.
> Gather Kuryr specific data

- collection-scripts/gather_network_logs
This commit fixes a typo on the retrival of the value
for the network type variable. Also, fixes the root path
of the network gathering to a path that allows writing
and is the same used by the gather script.
> Ensure correct value for netwok type variable

- collection-scripts/gather
openshift-kni-infra is the namespace where baremetal service pods
run. Currently it is not collected by must-gather which can make it
difficult to debug baremetal deployment issues. This adds the
namespace to the list of namespaces from which to collect logs.
> Bug 1829113: Add openshift-kni-infra namespace to gather

- collection-scripts/gather_network_logs
This fixes a problem in getting the master pod.
This captures the ovn database files on each master node
It also includes the node name in the file name of the
log files.
Bug 1834836
https://bugzilla.redhat.com/show_bug.cgi?id=1834836
SDN-946 - gather_network_logs - also capture sbdb and nbdb
https://issues.redhat.com/browse/SDN-946
> bug 1834836: gather_network_logs - capture sbdb and nbdb

- collection-scripts/gather
- collection-scripts/gather_etcd
One of the most important things to check while getting information from a cluster is to check the cluster etcd health. This cannot be achieved by just getting some pod logs or kubernetes resources, but needs its own set of commands to be run in etcd pods.
In this pull request, I am adding a `gather_etcd` script to gather that information and I also made it to be run by default from main `gather` script.
Having this information on every must-gather would be of great help for support.
I'll be happy to help with any change or improvement required on this. And thanks in advance.
> Gather etcd information from must-gather

- collection-scripts/gather_network_ovn_trace
This processes log files for namespace openshift-ovn-kubernetes.
It also captures the master and worker journals for kublet and crio.
It:
- formats time stamps into a common format
- adds a prefix to each log line consisting of:
- time stamp
- node name
- pod name
- container name
Extracts the log and previous log for each continer
- applies the prefix to each line
- combines all resulting files and
- sorts the results into the trace
- deletes work files.
SDN-975 - Logging: add must-gather networking-gather-trace script
https://issues.redhat.com/browse/SDN-975
> Trace ovn processing in cluster

- collection-scripts/gather
The MCO relatedObjects field grabs those
Signed-off-by: Antonio Murdaca <runcom@linux.com>
> collection-scripts/gather: drop MCO resources

- collection-scripts/gather_audit_logs
These files are placed there to notice failing graceful termination. As long as a kube-apiserver is running, they will exist. Hiding them is cosmetics, but it avoids confusion.
> gather-audit-log: skip .terminating files

- collection-scripts/gather
must-gather should collect these Kubernetes objects too:
* CSIDriver - information about installed CSI drivers (one per driver, usually few per cluster)
~* CSINode - information about CSI driver topology (one per node)~
> Add CSI storage objects

- collection-scripts/gather_network_ovn_trace
Backport https://github.com/openshift/must-gather/pull/156 and https://github.com/openshift/must-gather/pull/159 to release-4.5
--------------
PR 159 - Extract trace of ovn bringup
Scan through the generated trace for key lines in ovn bringup and report them.
SDN-1028 - Trace: generate trace of networking bring up
Trace: generate trace of networking bring up
--------------
PR 156 - Generate trace of ovn operation
This processes log files for namespace openshift-ovn-kubernetes.
It also captures the master and worker journals for kublet and crio.
It:
- formats time stamps into a common format
- adds a prefix to each log line consisting of:
- time stamp
- node name
- pod name
- container name
Extracts the log and previous log for each continer
- applies the prefix to each line
- combines all …
> Bug 1849244: [release-4.5]Trace ovn processing in cluster

- collection-scripts/gather
- collection-scripts/gather_network_ovn_trace
- collection-scripts/gather_service_logs
- collection-scripts/gather_windows_node_logs
The '-u' flag for 'oc adm node-logs' cannot be used against Windows
nodes. This commit ensures that the '-u' method of collection is only
used for services running on Linux nodes, and the '--path' option is
used for collecting Windows node log files.
> Separate Linux and Windows node log collection

- collection-scripts/gather
VolumeSnapshotClasses, VolumeSnapshotContents and CSINodes are Kubernetes objects not related to any OCP operator.
CSINodes have OwnerReference to Nodes, however, `oc must-gather` does not track owners, see https://bugzilla.redhat.com/show_bug.cgi?id=1861650.
These objects are available on OCP 4.4 and newer.
/assign @sferich888
> Gather more storage objects

- collection-scripts/gather_core_dumps
- collection-scripts/gather_network_logs
This PR implements more log collection for Openshift Networking,
with OVN-Kubernetes
-It fixes https://bugzilla.redhat.com/show_bug.cgi?id=1868716
-Specifically it adds the collection script `gather_core_dumps`
to collect core dumps on hosts
-Zips the ovn-nb/sb.db files and adds flow/port
dumping for the br-ex interface in `gather_network_logs`
-Ensures for both `gather_network_logs` and `gather_core_dumps`
that we only query linux based nodes
-Leaves the networking logging off by default in `gather`
-to run the networking collection scripts use the following
command:
`oc adm must-gather -- gather && gather_core_dumps &&
gather_network_logs && gather_network_ovn_trace`
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
> Bug 1868716: Implements more log collection for Openshift networking

- collection-scripts/gather_network_logs
It is very helpful to understand the details of host network interfaces to understand issues such as dropped packets. This PR adds `ip -s -d link` tot he current list of ip command outputs collected. This command was previously part of `sosreport`.
> Bug 1874301: collection-scripts/gather_network_logs: add detailed status for interfaces

- collection-scripts/gather_core_dumps
The previous iteration of `gather_core_dumps` used
`coredumpsctl info` to get information
It was shown that we in fact need the raw coredump
files for debugging
This PR extracts corefiles from the nodes by
1. Forcing a Debug pod to stay open on node
2. Waiting for the Debug pod to run
3. Using `oc cp` to extract the necessary files
TODO: find a way to do this without forcing the
debug pod to stay running
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
> Bug 1877428: Update gather_core_dumps to get raw coredump files 

- collection-scripts/gather_core_dumps
This Commit fixes the failed validation on 
PR https://github.com/openshift/must-gather/pull/173`
in response to the [feedback from QA](https://bugzilla.redhat.com/show_bug.cgi?id=1877428)
It updated how the name of the debug pod is
determined
Specifically it uses `sed` to extract the pod name
when the pod is created with `oc debug` rather than 
using `oc get` to try and determine the name after the fact
since there is more room for errors in string formatting 
Also ensures that the debug pod is delete the moment we 
are finished with it rather than allowing it to hang 
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
> Bug 1877428: Update gather_core_dumps collection of debug pod's name, clean up resources 

- collection-scripts/gather_core_dumps
There were still some edge case bugs here
involving the script's integration with
must-gather
This commit fixes it by getting the debug pod's
name and and now namespace in a much more 
robust manner
specifically it uses `oc debug -o jsonpath` to
determine the name of the debug pod prior to
actual pod creation rather than bash string 
processing
It also extends the time a debug pod may persist
to 5 minutes in the case of large coredump files
that need to be extracted from the nodes.
lastly it cleans up some bash script formatting 
issues
Signed-off-by: Andrew Stoycos <astoycos@redhat.com>
> Bug 1877428: Increase gather_core_dump robustness after seeing some CI issues

- collection-scripts/gather_network_logs
Since we switched to host OVS, it is useful to gather it.
> Bug 1868794: Gather OVS logs from host

- collection-scripts/gather_core_dumps
The previous iteration of `gather_core_dumps` broke
CI because some unexpected behaviour was exhibited
where `oc debug` would make a new namespace for
the `debug` pod that we use to copy the coredumps
off each node
This commit fixes that by forcing `oc debug` to spawn
it's debug pod in the `default` namespace by using
the --to-namespace flag
It also adds a bit of extra logging
> Bug 1877428: Update `gather_core_dumps` to fix unexpected behavior in CI

- collection-scripts/gather
- collection-scripts/gather_audit_logs
- collection-scripts/gather_service_logs
* simplified logic
* added progress logging
* also capture oauth-apiserver logs
* add `SINCE_TIMEFRAME` env, defaulted to `1w`
> Bug 1862426: gather the audit logs for oauth apiserver

- collection-scripts/gather_network_logs
`app=sdn` pods added a `kube-rbac-proxy` container so we
should now specify the `sdn` container explicitly when
execing in the sdn pods.
Thin prevents the warnings:
```
[must-gather-dbslg] POD Defaulting container name to sdn.
[must-gather-dbslg] POD Use 'oc describe pod/sdn-ljds8 -n openshift-sdn' to see all of the containers in this pod.
```
> gather_network_logs: specfiy sdn container for sdn pods

- collection-scripts/gather
- collection-scripts/gather_olm
We've had some requests for this - it may be controversial, but this seemed as good a place as any to collect feedback.
> Add olm resources to default must-gather

- OWNERS
/assign @sttts 
Can you please review to help me push this through.
> Adding Bugzilla component information to must-gather

- collection-scripts/gather_network_logs
The Way information was collected here for EgressIP,
EgressFirewall and NetworkPolicies was not scalable
and showed some problems under scale testing
Instead those objects will be included under
networking's related objects so that `oc adm inspect`
will automatically collect the required data
> Remove namespace

- collection-scripts/gather_windows_node_logs
Use the Get-WinEvent shim on kubelet logs endpoint introduced in
https://github.com/openshift/kubernetes/pull/383 to collect docker
runtime logs from Windows machines.
/cc @sebsoto @aravindhp 
/cherry-pick release-4.6
> Bug 1862643: Collect docker logs from WinEvent log on Windows machines

- collection-scripts/gather
If kubernetes-nmstate is on a cluster, these resources would be helpful
to ascertain what possible network configurations on present on nodes.
> Bug 1906968: Add kubernetes-nmstate resources to must-gather

- collection-scripts/gather_network_logs
This commit includes the support to gather more Kuryr data
for the Custom Resources and remove resources that are not
supported anymore.
> Bug 1916417: Gather Kuryr CRDs data

- collection-scripts/gather_network_logs
Description
extending must gather network logging to include ovs db dump to enhance debugging.
Type of change
Enhance debugging of openshift cluster.
How Has This Been Tested?
created Openshift cluster ob GCP
run must gather using my special image from qauy
```
oc adm must-gather --image=quay.io/mmahmoud/must-gather-test:1.1 gather_network_logs
```
check conf.db files is gathered for all nodes
/home/mmahmoud/data/must-gather.local.5971192883354181951/quay-io-mmahmoud-must-gather-test-sha256-0cc86c9604173fe30cde33abcdcd0b71eebd9701a94b0635464edb61ed5d01e9/network_logs
[mmahmoud@mmahmoud network_logs]$ ls -l *conf.db
-rw-r--r--. 1 mmahmoud mmahmoud 887425 Mar 24 07:44 ovnkube-node-7ntlv_conf.db
-rw-r--r--. 1 mmahmoud mmahmoud 166369 Mar 24 07:44 ovnkube-node-gwzqh_conf.db
-rw-r--r--. 1 …
> Bug 1916809: extend must-gather network log to include nodes' ovs DB

- collection-scripts/gather_audit_logs
Skip .lock file from https://github.com/openshift/cluster-kube-apiserver-operator/pull/1128.
> Bug 1958094: gather_audit_logs: ignore .lock file

- .ci-operator.yaml
Preparation for https://github.com/openshift/must-gather/pull/228.
> Bug 1953563: Add .ci-operator.yaml with build_root_image

- collection-scripts/gather_audit_logs
https://github.com/openshift/cluster-etcd-operator/pull/596 adds health audit logs for etcd. This PR adds those logs to the audit_logs gather script. This script is already known by support and users and the etcd state should not be large in size. Piggybacking the logs along with the other control-plane components seems logical.
alternative : https://github.com/openshift/must-gather/pull/236
> Bug 1958405: add etcd health logs to audit

- collection-scripts/gather_monitoring
This patch gathers more monitoring data from
1. `Prometheus` such as
* rules
* altermanagers
* status/config
* status/flags
* status/runtimeinfo
* status/tsdb
2. `AlertManager` such as
* /api/v2/status
JIRA: https://issues.redhat.com/browse/MON-1234
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> Gather more monitoring data

- README.md
- collection-scripts/gather
- collection-scripts/gather_network_logs
Fix ip route gathering (command should be evaluated inside OVNKUBE_NODE_POD)
Fix evaluating if ipsec is enabled (condition evaluation previously failed, always returning False condition result)
Add How to run section to README.md
> Minor fixes for gather_network_logs

- collection-scripts/gather
This namespace is now handled properly by relatedObjects in MCO, so
we no longer need to have it listed explicitly here.
> Remove openshift-kni-infra namespace from gather script

- collection-scripts/gather_network_logs
Change the way of gathering ovs db from compacting + copying db files to ovsdb-client backup.
This change should solve the following problems:
- copying the .db file might pick partial data
- even after compacting, it's not guaranteed that there are no transactions (which could happen after compacting and before copying the file). This makes it difficult for parsers other than ovsdb-server, e.g: insights.
Also, files from ovsdb-client backup may be used by ovsdb-client restore for local debugging.
Test:
Run must-gather, check `network_logs/<OVNKUBE_MASTER_POD>_nbdb.gz` and `network_logs/<OVNKUBE_MASTER_POD>_sbdb.gz` files.
Example of previous nbdb file:
```
OVSDB CLUSTER 147818 853ae92cae5be5e42481dc8f3d5a1fa390512145
{
"cluster_id": "9f6509ea-c238-40c5-9c36-ade7b0c84b8c", …
```
> Bug 1974364: Change the way of gathering ovn db

- collection-scripts/gather
- collection-scripts/gather_kas_startup_termination_logs
the logs are optional and stored at `/var/logs/kube-apiserver/startup.log` and `/var/logs/kube-apiserver/termination.log` on the host.
the script will save it under `must-gather/static-pods/kube-apiserver`
> introduces a script for collecting kas static pod logs

- collection-scripts/gather_monitoring
Collect Monitoring data for each Prometheus replica in the following endpoints:
- `status/tsdb`
> feat/monitoring: gather replica specific data

- collection-scripts/gather_audit_logs
This PR is part of the Monitoring story[1] to enable audit logs for
Prometheus Adapter[2]. The patch adds the functionality to gather
audit logs from prometheus-adapter pod which is available from
OpenShift version 4.10.
Running `oc adm must-gather -- /usr/bin/gather_audit_logs` will now
gather prometheus-adapter audit logs and will be stored under
`monitoring/<prometheus-adapter-pod>` directory.
[1]: JIRA: https://issues.redhat.com/browse/MON-1786
[2]: https://github.com/openshift/cluster-monitoring-operator/pull/1377
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> MON-1786: Enable collection of prometheus-adapter audit logs

- collection-scripts/gather
Currently, the pod logs API does not expose [rotated logs](https://github.com/kubernetes/kubernetes/blob/b0bc8adbc2178e15872f9ef040355c51c45d04bb/pkg/kubelet/kuberuntime/logs/logs.go#L42). 
By using the flag introduced [here](https://github.com/openshift/oc/pull/958) must-gather will collect all of the available rotated log files for the selected containers.
Default OpenShift settings:
`containerLogMaxFiles: 5`
`containerLogMaxSize: 50Mi`
Rotation happens once current log file reaches `50Mi` in size and there can be up to 5 log files per container
**Although the rotated logs are [compressed](https://github.com/kubernetes/kubernetes/blob/91b7fb4dc9f5d98583ee63be51dac7b6c0704b10/pkg/kubelet/logs/container_log_manager.go#L289) this change may result in a significant size increase of the …
> Collect rotated log files

- collection-scripts/gather
- collection-scripts/gather_metallb_logs
Add script for gathering metallb logs.
The script checks if the metallb-operator is installed via the operator subscription (by running `oc get subs...`)
more details about the data that's being gathered in the commit description.
> Add capability for MetalLB logging

- collection-scripts/gather_metallb_logs
changing the MetalLB speaker component label back to the old
version as this change produced bugs on MetalLB and the label
was reverted there as well.
[changed from: app.kubernetes.io/component=speaker to: component=speaker]
> Bug 2041087: Revert MetalLB  speaker component label

- collection-scripts/gather_profiling_node
Allow to collect kubelet profiling data when required:
oc adm must-gather -- gather_profiling_kubelet $NODE
This would help diagnosing issues in the kubelet.
(https://issues.redhat.com/browse/OCPNODE-698)
> Add script to collect kubelet profiling data

- collection-scripts/gather_monitoring
This patch is related to [MON-1234](https://issues.redhat.com/browse/MON-1234) Jira issue. The 4d36ee0f which
originally addressed the ticket missed collecting Prometheus target
information which this patch addresses.
Additionally, this PR ...
1. Fixes a script error (introduced in d21e69ee) caused due to
usage of an uninitialized variable - PODS
2. Makes proper use of array to iterate prometheus pods
3. Makes "path" parameter to `prom_get` and `alertmanager_get` functions
optional to improve  readability. I.E. it now supports both
*  `prom_get rules`
*  `prom_get rules?type=alert  rules/alerts`
4. Passes shellcheck once again
See: https://issues.redhat.com/browse/MON-1234
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> [MON-1234] Collect prometheus target details

- collection-scripts/gather_profiling_node
Add collection of CRI-O profiling data in the gather_profiling_node script (introduced in #273).
The script is not run by default. When run, it will now collect CRI-O profiling data besides profiling data from the kubelet.
The user can force collection of either CRI-O or kubelet data using the env var PROFILING_NODE_TARGET: allowed values are 'all', 'crio' or 'kubelet'.
oc adm must-gather -- PROFILING_NODE_TARGET=crio gather-profilng-node
This PR is based  on the suggestions from #260 .
> collection-scripts: allow collection of CRI-O profiling data

- collection-scripts/gather_etcd
Picking a pod to run `etcdctl` commands on must be more selective, as `openshift-etcd` namespace started running "quorum-guard" pods as well. This change ensures the logic works no matter how the cluster nodes are named.
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>
> RUNNING_ETCD_POD must not be a quorum pod for must-gather

- collection-scripts/gather_metallb_logs
Currently, the gather_metallb_logs script is extracting the operator
namespace by selecting the subscription with the metadata.name equal
to "metallb-operator". However, it would be more correct to check
against the spec.name that points to the name of the operator,
as the value of this field is constant. unlike the other that can
be called "metallb-operator-sub".
Note that I didn't use `--field-selector` in the new implementation
as spec.name field label is not supported.
> Bug 2054319: Fix the namespace extract filter

- collection-scripts/gather_windows_node_logs
This PR adds the containerd runtime logs in the `must-gather` for Windows nodes.
> WINC-708: Collect containerd logs on Windows instances

- collection-scripts/gather_etcd
Adding change to list the pods by label app=etcd to only list etcd pods. 
Also removing the need of greping -v the quorum pods.
Signed-off-by: Vladislav Walek <22072258+vwalek@users.noreply.github.com>
> List the pods by label app=etcd to only list etcd pods

- collection-scripts/gather
- collection-scripts/gather_nmstate
Currently we are missing the NMState resources in the must-gathers. This is especially a problem as the kubernetes-nmstate-operator became GA in 4.10. 
This PR addresses it and adds the NMState resources (namespace resources & CRs) to the must-gathers when the operator is installed.
**Hints for reviewers:**
I was following a similar approach to how MetalLB is collecting its resources ([./collection-scripts/gather_metallb_logs](https://github.com/openshift/must-gather/blob/master/collection-scripts/gather_metallb_logs)). If there is an easier way (e.g. by adding a certain annotation), please let me know.
**How to verify:**
1. Deploy a cluster and install the NMState operator (e.g. via the marketplace)
2. Add the NMState CR:
```
cat <<EOF | oc apply -f -
apiVersion: nmstate.io/v1
kind: …
```
> Bug 2062355: Collect NMState resources when operator is installed

- collection-scripts/gather
- collection-scripts/gather_metallb
- collection-scripts/gather_nmstate
Make use of `oc adm inspect` to collect custom resources to align the
resource collection with the must-gather folder structure and not
have to set it up manually.
**Info for reviewers:**
MetalLB stores its CRs currently in `${BASE_COLLECTION_PATH}/namespaces/${METALLB_NS}/cr/${CRD_NAME}.yaml`. `oc adm inspect -n ${METALLB_NS} ${CRD}` will store it now in `${BASE_COLLECTION_PATH}/namespaces/${METALLB_NS}/<API_GROUP_NAME>/<API_RESOURCE_PLURAL>/<CR_NAME>.yaml` like described in the doc:
https://github.com/openshift/must-gather/blob/26dcac9e3454eba950b7a9c36abae8ee537e7f21/must-gather.md#L219-L226
**How to verify:**
* For NMState: Same procedure as in #292
* For MetalLB:
* Deploy a cluster with this PR and install the MetalLB operator (e.g. into namespace metallb-system)
* Create the MetalLB …
> Simplify CRD collection

- collection-scripts/gather_metallb
MetalLB was introduced with 4 new CRDS:
bgpAdvertisements, ipaddresspools, l2advertisements and communities
This PR adds them to the collected CRs.
> Add new metallb crds to the gather script

- collection-scripts/gather_profiling_node
When trying to collect CRI-O profiling data from a Node in the NotReady
state, the script gets stuck and will never complete, blocking on the
deletion of the CRI-O collection pod (which gets stuck in the  "Terminating"
state).
When the collection pod fails, force its deletion.
https://issues.redhat.com/browse/OCPNODE-983
> gather_profiling_node: correctly manage NotReady Nodes

- collection-scripts/gather
- collection-scripts/gather_sriov
This PR adds SR-IOV gather script.
Gathering the following:
* openshift-sriov-network-operator namespace.
- sriovnetworknodepolicies.
- sriovnetworknodestates.
- sriovnetworkpoolconfigs.
- sriovnetworks.
- sriovoperatorconfigs.
- sriovibnetworks.
* The following logs from the sriov-config-daemon:
- /tmp/sno-initial-node-state.json. 
- /proc/cmdline.
- dmseg.
- ip link.
- var/multus.log (if exists).
- netns and output of `ip a` fron every ns.
- NIC firmware and driver from ethtool.
> Add SR-IOV gather script

- collection-scripts/gather
Some clusters might disable some core resources. This causes
must-gather failing while trying to get these disabled resources and
can not proceed to other ones.
This PR adds filtering for core resources by checking they exist in
cluster or not.
> Bug 1999529: Filter disabled resources in inspection to proceed others

- collection-scripts/gather_network_logs
without --no-headers option name is prefixed with \n
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
> Bug 2023295: fix getting deployment name

- collection-scripts/gather_monitoring
Issue: https://bugzilla.redhat.com/show_bug.cgi?id=2097346
problem: since k8s 1.24 tokens for SA are not automatically generated [1]
hence, it's not possible to get a SA token with the command
"oc sa get-token default", this breaks the gather_monitoring script as
we need the token to make http requests to prometheus
solution: use instead the new command "oc create token default"
[1] https://github.com/kubernetes/kubernetes/pull/108309
> Bug 2097346: Updates how gether_monitoring obtains SA token

- collection-scripts/gather_network_logs
Backport of https://github.com/openshift/must-gather/pull/307
In 4.9 `gather_scale_data` function is not present, skip that change
`openshift-cloud-network-config-controller` was only added from 4.10, skip that change too
> [release-4.9] Bug 2092265: Add networking resources

- collection-scripts/gather_windows_node_logs
With the switch to containerd as default runtime, we no longer want
to collect logs logs for the Docker Windows service.
> Stop collecting Docker logs on Windows instances

- collection-scripts/gather_haproxy_config
This fixes a bug where if router pods are stuck in terminating when doing a must-gather, the must-gather will timeout instead of waiting for the router pods to terminate. More specifically, we have a bug in 4.10 CI in which the e2e-aws-operator job consistently fails on e2e-aws-operator-gather-must-gather container test due to pods stuck in the `terminating` state. 
Two reasons why this happens in CI:
1. If the `oc cp` command is ran on `terminating` pods, it will hang until the pod is deleted.
2. Router pods ignore SIGTERMs sent immediately after starting up and will get "stuck" in terminating state until the `terminationGracePeriodSeconds` sends a SIGKILL. This results in a number of old router pods just hanging out in the terminating state. Backport is pending for 4.10 …
> Bug 2103283: Add timeout to oc cp command to fix must-gather delays when routers are terminating

- collection-scripts/gather
- collection-scripts/gather_podnetworkconnectivitycheck
Added a script to collect PodNetworkConnectivityChecks to able to view the overall status of the pod network connectivity.
Current must-gather collects the contents of `openshift-network-diagnostics` but does not collect the PodNetworkConnectivityCheck.
> Added PodNetworkConnectivityCheck gather script

- collection-scripts/gather_network_logs
Adds HostSubnets to the `gather_network_logs` script to resolve #298 
Sample output:
```bash
$ tree cluster-scoped-resources/network.openshift.io/
cluster-scoped-resources/network.openshift.io/
├── clusternetworks
│   └── default.yaml
└── hostsubnets
├── master-0.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
├── master-1.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
├── master-2.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
├── worker-0.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
├── worker-1.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
└── worker-2.sharedocp4upi48.lab.upshift.rdu2.redhat.com.yaml
```
Submitted new PR after accidentally deleting the wrong branch. Previous PR #335
> Added hostsubnets to group_resources in gather_network_logs script

- collection-scripts/gather
- collection-scripts/version
Fix the generation of the `/must-gather/version` file such that if multiple must-gather images are invoked at once, the only the version of the currently running image will be recorded in the `/must-gather/version` file.
If a semantic-like version cannot be parsed from the image's `repository:tag` name (note that `:latest` is not a semantic-like version), use the imageID (typically a `repository@digest`) value.
> report correct version when multiple images invoked

- collection-scripts/gather_windows_node_logs
This PR updates the kube-proxy log file name to sync with the recent changes made in the kube-proxy log collection implementation.
> WINC-977: Update kube-proxy log file name

- collection-scripts/gather
- collection-scripts/gather_custom_metrics_autoscaler_logs
This changes adds the gather script for the Custom Metrics Autoscaler (CMA) operator so that the operator resources are included in the must-gather if the operator is present.
Gathering the following:
- kedacontroller,
- scaledjob,
- scaledobject,
- triggerauthentication,
- clustertriggerauthentication and
- subscription namespace, e.g. ns/openshift-keda
> OCPNODE-1499: Add CMA gather script

- collection-scripts/gather_audit_logs
The PR https://github.com/openshift/must-gather/pull/259 fixed the bug [2014995](https://bugzilla.redhat.com/show_bug.cgi?id=2014995), but we don't back-port it to release 4.9. It will cause the same issue with 4.9 release. This PR will back-port the code to 4.9 release, fixed the bug https://issues.redhat.com/browse/OCPBUGS-7916.
> OCPBUGS-7916: Back-port #259 to release 4.9

- collection-scripts/gather_network_logs
Extend multus resource collection so that we gather all resources on a per namespace basis with `oc adm inspect`.
This way, users can create a combined must-gather with all resources in one place.
We might have to revisit this once the reconciler and other changes land in more recent version of multus, but for the time being I think that this is a good change to make that we can also bp to older versions
-------------------------
Test image with this change:
~~~
oc adm must-gather --image=quay.io/akaris/must-gather:take0 -- "/usr/bin/gather ; /usr/bin/gather_network_logs"
~~~
Here's the output of a test must-gather image with this change:
~~~
[akaris@linux 03402332]$ find must-gather.local.5408551214882970458/ -ipath '*network_logs*' …
> OCPBUGS-11147: network_logs: Gather multus resource yamls for namespaces

- collection-scripts/gather
Fixes: [must-gather does not contain CSIStorageCapacity](https://issues.redhat.com/browse/OCPBUGS-10798)
After building and deploying `must-gather` image to a cluster:
```
apiVersion: storage.k8s.io/v1
capacity: 15442104Ki
kind: CSIStorageCapacity
maximumVolumeSize: 31970284Ki
metadata:
creationTimestamp: "2023-03-01T10:25:09Z"
generateName: csisc-
labels:
csi.storage.k8s.io/drivername: kubevirt.io.hostpath-provisioner
csi.storage.k8s.io/managed-by: external-provisioner-crc-9ltqk-master-0
...
```
> OCPBUGS-10798: Gather CSIStorageCapacity objects

- collection-scripts/gather
- collection-scripts/gather_network_observability
New script to collect netobservability logs and enable it by default
```shell
oc adm must-gather
```
Testing with cluster-bot
========================
1- Create must gather for network-observability
```shell
oc adm must-gather
```
2- Check the pods using `omg` tool
```shell
$ omg use must-gather.local.2028201061218736439/
Using:  /home/mmahmoud/data/test-noo-mg/must-gather.local.2028201061218736439/registry-build02-ci-openshift-org-ci-ln-tp5qw22-stable-sha256-da661034dc54b9943a1ce6c9b2abbb56c4ade39d1640ffe13a2f2a8e0867f7e0
$ omg get pods -n netobserv
NAME                               READY  STATUS   RESTARTS  AGE
flowlogs-pipeline-4f8t7            1/1    Running  0         6m53s
flowlogs-pipeline-7slt6            1/1    Running  0         6m53s
flowlogs-pipeline-dbgs4            1/1 …
```
> NETOBSERV-987: Add must gather script for network observability

- collection-scripts/gather
- collection-scripts/gather_vsphere
Collect vSphere CSI driver CRD instances. The script does not do anything on other platforms.
The CRs will be useful when debugging storage issues on vSphere.
@openshift/storage
> OCPBUGS-14025: Add gather_vsphere

- collection-scripts/gather_sriov
We need to be able to collect firmware specific information when Bluefield/Mellanox devices are being used with SRIOV.
This commit uses mstflint to add this information to the must-gather when such NICs are detected.
> OCPBUGS-14984: Collect Mellanox firmware information

- collection-scripts/gather
- collection-scripts/gather_machineconfig_ondisk
There have been a lot of Machine Config Operator (MCO)  bugs recently (e.g.  https://issues.redhat.com/browse/OCPBUGS-12741) where the MCO doesn't render the same thing during bootstrap and live operation, usually due to race conditions introduced elsewhere. 
We want these sorts of issues to cause degradation rather than silently succeed so we can catch rendering issues and race conditions, but troubleshooting them hurts a lot right now because there are on-disk files we need to see that we can't. (We often have to ask reporters/customers to manually collect the files for us) 
This PR adds a gather script that:
-  collects the on-disk `currentconfig` and `mcs-machine-config-content.json` from any node the MCO has marked degraded
With this, you end up with something like this in the …
> MCO-608: Gather MCO's on-disk configs from degraded nodes

- collection-scripts/gather_ingress_node_firewall
- collection-scripts/gather_metallb
- collection-scripts/gather_network_observability
- collection-scripts/gather_nmstate
- collection-scripts/gather_sriov
Users that mistakenly misconfigure and create two instances (or more)
of the subscription resource causes some gather scripts to fail.
For example, with 2 different sriov subscriptions, the SRIOV_NS will equal
"openshift-sriov-network-operatoropenshift-sriov-network-operator" which is invalid.
Here we add "{{\n}}" and with that, check whether we found more than
one subscription, and if so, exit with an error.
This fix is applied to all of the gather scripts that use this method:
ingress_node_firewall, metallb, network_observability, nmstate and sriov
> Assert that only one subscription exists

- collection-scripts/gather
This commit adds the leases resource to the list of resources to collect from all namespaces.
fixes #364
> Collect leases.coordination.k8s.io from each namesapce

- collection-scripts/gather_network_logs
As reported by surya:
~~~
not sure if you are the right person but pinging you based on : https://github.com/openshift/must-gather/pull/354 commit history :thread2:; when I run a must-gather on 4.14 latest I see:
error: the server doesn't have a resource type "multi-networkpolicy"                                                                                                         
error: the server doesn't have a resource type "multi-networkpolicy"                                                                                                         
which is not fatal but maybe we want to fix it to be smooth
~~~
> gather_network_logs: multus: Fix typo in error redirection

- collection-scripts/gather
- collection-scripts/gather_ppc
This PR adds support for collecting data related to the PerformanceProfile CR (provided by a core OCP operator - Cluster Node Tuning Operator) operation and creation [4].
The code used to live in a separate repository [5], but the Performance Profile logic became part of NTO in OCP 4.11 ([1][2]).
There are two major pieces added:
- The gather_ppc script (ppc stands for Performance profile controller) which is a pretty common gather script with one exception. It starts a daemon set re-using the must gather image itself, but with extra host volumes (/proc, /sys, ..) to be able to collect some low level hardware data. Some it collects directly using oc exec, some it uses gather_sysinfo for.
- The gather_sysinfo binary that uses the ghw [3] library to collect some extra low level data about …
> Collect information relevant to PerformanceProfile and low latency tuning

- collection-scripts/gather_windows_node_logs
Follow-up to:
- https://github.com/openshift/windows-machine-config-operator/pull/1530
> Add csi-proxy logs collection in must-gather for Windows nodes

- collection-scripts/gather_ppc
The previous method of using oc adm release info has been problematic for CI and restricted network environment clusters.
The issue was always the authentication to the registry and access to the release image from the inside of must-gather.
Also the oc adm release info tool runs inside a container and does not respect the node level ImageContentSourcePolicy.
For all these reasons I want to retrieve the image name from the configured NTO deployment instead.
> Use oc get daemonset to identify the NTO image

- collection-scripts/gather_ppc
This PR proposes a fix for this [bug](https://issues.redhat.com/browse/OCPBUGS-19761).
As @MarSik has commented, we believe the bug was created because the daemonset deploying pods with workload partitioning, whilst workload partitioning is not enabled for the MG temporary namespace.
To fix that, I removed the workload partitioning from the daemonset spec. Therefore, the pods that will now be deployed won't require workload partitioning to be enabled.
> OCPBUGS-19761: Removed workload partitioning annotation from ppc script

- collection-scripts/gather_ppc
PerformanceProfile creates a RuntimeClass.
It would be nice to have that in the must-gather information so lets explicitly gather that information in the script
> ppc: explicitly add RuntimeClass to gathered resources

- collection-scripts/common.sh
- collection-scripts/gather_sriov
`ip netns` output can have trailing strings after the
network namespace name, e.g.:
```
0e7432cc-0577-4e11-a88f-3ce8182dcd3f
f6f51cfd-02c5-45d7-917d-fc359d95df71
3ec15511-a387-40e6-a7c6-2de71b7bf880 (id: 27)
8ef1a9d8-be3f-44cb-9288-712eb3e4436f (id: 26)
```
Ensure every string after the space is filtered out.
Also, removing `set -e` statement from `common.sh`
> sriov: Clean up `ip netns` output 

- collection-scripts/gather_machineconfig_ondisk
The current logic collects either the MCS served config or currentconfig for installation failures. This doesn't really help since the currentconfig gets written by a firstboot service, and contains only a very small encapsulated MachineConfig generally speaking.
Change the script to always collect the MCS served config since this helps with rendered-master-xxx not found bugs, which otherwise we can't easily get.
> machineconfig: always gather MCS-served config

- collection-scripts/gather
To save time when running the OCP MG, the collection scripts can be executed in parallel.
Process:
1.Collect script
2.Waiting on subprocesses to finish execution.
Tested on my cluster and we can save 20% run time:
```
oviner:my_image$ time oc adm must-gather --image=quay.io/oviner/ocs-must-gather:ocp_mg2
real    7m49.209s
user    0m13.960s
sys     0m4.095s
oviner:regular_image$ time oc adm must-gather --image=quay.io/openshift/origin-must-gather:latest 
real	9m44.340s
user	0m14.055s
sys	0m4.115s
```
> NO-JIRA: Running gather scripts in background

- collection-scripts/gather_metallb
Add a timeout in "oc exec -c frr -- vtysh -c ${COMMAND}" This command can block if vtysh is not responding properly and can put customer into a situation where mustgather can not be grabbed.
> NO-JIRA: Update gather_metallb

- collection-scripts/gather
- collection-scripts/gather_aro
Azure Red Hat OpenShift (ARO) contains its own operator and custom resource, as well as a few additional namespaces on top of the base OCP. If accepted, this PR would collect this data if present or skip if not present, so that ARO customers can collect must-gathers that will help MCS and SRE debug ARO-specific issues.
Currently, this change is available in a custom must-gather image at `quay.io/cmarches/aro-must-gather`, but I wanted to propose adding the change upstream since ARO is an official OCP flavor and not all Azure customers will be able to pull a custom image from quay for compliance reasons.
> NO-JIRA: Add ARO support to must-gather client

- collection-scripts/gather_network_logs_basics
This PR adds support to must-gather for collecting crds of globally scoped resource: ANP.
See https://issues.redhat.com/browse/SDN-4157 for downstream details
See https://network-policy-api.sigs.k8s.io/reference/spec/ for API reference.
Tested on 4.16 cluster:
```
[must-gather-pc2zx] OUT ./cluster-scoped-resources/policy.networking.k8s.io/adminnetworkpolicies/node-as-egress-peers.yaml                                                   
[must-gather-pc2zx] OUT ./cluster-scoped-resources/policy.networking.k8s.io/adminnetworkpolicies/trial.yaml                                                                  
[must-gather-pc2zx] OUT ./cluster-scoped-resources/policy.networking.k8s.io/adminnetworkpolicies/trial3.yaml …
```
> SDN-4597: Add cluster scoped ANP resource to collection

- collection-scripts/gather_metallb
This PR adjusts the must gather collect script to reflect the latest metallb:
- it checks for the bgp backend and collect from the frr-k8s / speaker frr container according to the bgp backend
- it removes fetching the addresspool resource that was removed
Also, minor fix in fetching the pid from the right path.
> CNF-9168: MetalLB: adjust to support frrk8s and small fix

- collection-scripts/gather
Adds the namespace for the Assisted Installer to collect the Assisted Installer Operator logs when a must-gather is run.
> OCPBUGS-32210: Collect Assisted Installer Namespace Logs

- Dockerfile.rhel7
must-gather includes oc invocations to gather some data and must-gather gets this oc from cli image. However, when we try to bump cli image to RHEL9, since must-gather is still on RHEL8, all oc invocations failed. This PR changes to use cli-artifacts image instead of cli. Thanks to that change, must-gather can explicitly uses oc.rhel8 and that decouples the cli and must-gather images for the future similar migrations.
example failures;
*  https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oc/1752/pull-ci-openshift-oc-master-e2e-aws-ovn/1784837264291926016
* https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_oc/1752/pull-ci-openshift-oc-master-e2e-agnostic-ovn-cmd/1784837260940677120
> NO-JIRA: Use oc rhel8 binary explicitly until base image is rhel9

- Dockerfile.rhel7
This PR uses the correct oc.rhel8 binary based on the image's architecture. This is the follow up of https://github.com/openshift/must-gather/pull/418
> WRKLDS-1251: Use oc.rhel8 based on the target arch of image

- .ci-operator.yaml
- Dockerfile.rhel7
This reverted back the changes done to use explicit oc.rhel8. Since, oc is now moved to RHEL9, this PR switches must-gather to RHEL9 and uses the binary in the cli image.
> WRKLDS-1257: Switch must-gather to RHEL9 as base image

- collection-scripts/gather_network_logs_basics
Previous to this change, debug pods will be launched to node that are unready and deployment will not complete.
Also update control plane label selector.
/cc
~/hold~
> OCPBUGS-33959: Network logs collection: skip unready nodes

- collection-scripts/gather_ppc
Add toleration to perf-node-gather DaemonSet to ensure PerformanceProfile related data is collected from all nodes in a cluster.
The PerformanceProfileCreator tool, found within the Node Tuning Operator will return errors if the necessary files are missing for tainted cluster nodes. The data is collected using this DaemonSet in must-gather
Nodes are expected to be tainted for various reasons such as Infrastructure nodes, master nodes etc
> OCPBUGS-31037: Collect PerformanceProfile Data From all Nodes

- collection-scripts/gather_ppc
- collection-scripts/gather_ppc_single_node
The PPC node data collection was running in serial and that increased the time needed to collect the whole cluster. This change executes each per-node sequence in parallel and waits for all the sub tasks.
The only disadvantage is having a per-node process (potentially hundreds in huge clusters), however this case has always been lower in the code as well. The load on the controlling must-gather pod should be low as it only executes remote commands and waits for results.
This can be tested (at least while the PR is open) by executing:
```
oc adm must-gather --image quay.io/msivak/must-gather:test416c
```
Thanks to our scale testing colleagues we have a comparison between the stock and the parallelized runs using OCP 4.16.0-rc.3 on a cluster with 120 worker nodes.
stock:
```
$ time oc adm …
```
> OCPBUGS-34360: Run ppc node collection in parallel

- collection-scripts/gather_metrics
- collection-scripts/gather_monitoring
- collection-scripts/monitoring_common.sh
This introduces a new `gather_metrics` script. The script leverages the new `promtool tsdb dump-openmetrics` command to extract metrics in OpenMetrics format.
The script accepts some arguments, run:
$ ./collection-scripts/gather_metrics
for more details.
The dumpoed metrics can be imported into a Prometheus instance using:
$ promtool tsdb create-blocks-from openmetrics
For more information, refer to https://prometheus.io/docs/prometheus/latest/command-line/promtool/#promtool-tsdb-create-blocks-from
Note that in some cases, using `increase()` or `{i}rate()` functions on the imported data may return negative or inaccurate results. This issue is under investigation and will be fixed upstream.
Recommendations:
- Import these metrics into a blank Prometheus instance.
- Ensure that the major …
> MON-3108: Add gather_metrics for Prometheus fetching

- collection-scripts/gather_ppc
gather_ppc script is looking for NTO image, becuase it contains all the tools that needed.
On Hypershift platfrom, the control-plane components are located on a different cluster, so the script can't find NTO image since the controller is running on the remote (management) cluster.
This commit suggests to add a fallback method:
In case NTO deployment was not found, the script tries to get NTO image name from the release image.
Signed-off-by: Talor Itzhak <titzhak@redhat.com>
> CNF-13837: gather_ppc: fallback option when NTO image not found

- collection-scripts/monitoring_common.sh
So users don't have to set it.
https://github.com/openshift/must-gather/pull/434 follow up.
This is a temporary fix until the upstream change is merged https://github.com/prometheus/prometheus/pull/14617 and shipped in OCP 
See https://prometheus.io/docs/prometheus/latest/command-line/promtool/#promtool-tsdb-dump-openmetrics for the flag doc.
> MON-3108: fix(collection-scripts/monitoring_common.sh): set a default --sandbox-dir-root to 'promtool tsdb dump-openmetrics' for better UX

- collection-scripts/gather
- collection-scripts/gather_osus
Collect data from OSUS operator if installed in the cluster.
> OTA-1177: Gather OSUS data

- collection-scripts/gather_network_logs_basics
Previous to this change, debug pods will be launched to node that are unready and deployment will not complete.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
(cherry picked from commit 619862a66621e17258c5b1d3d5048970987f1eb5)
> OCPBUGS-42835: [Release-4.17] Network logs collection: skip unready nodes

- collection-scripts/gather_network_logs_basics
This PR collects IPsec related configs and logs as much as possible which helps to troubleshoot issues. This can not collect ipsec service logs while it's running on the host. Hence we need to rely on journal logs collected from the node filtering with pluto.
> OCPBUGS-42679: Support gathering IPsec data

- collection-scripts/gather_ppc
With the On Cluster Layering feature moving towards GA in in the MCO, we need to collect data on the two new kinds related to that. These are machineosconfigs and machineosbuilts.
> MCO-1418: Add collection for MOSC and MOSB

- collection-scripts/gather_network_logs_basics
This is an addendum to #445 -- which misses a fix Ben Pickard identified after its merge.
> OCPBUGS-42835: Removes reference to gather_multus_logs in 4.17

- collection-scripts/gather
Fix for: https://issues.redhat.com/browse/OCPBUGS-44857 
`oc adm inspect --all-namespaces` command was malformed, so its resources were never gathered.
> OCPBUGS-44857: Separate resources with comma to fix malformed inspect

- collection-scripts/gather
ClusterCSIDriver objects are small, let's collect them all. We expect that there 4 ClusterCSIDriver instances in a cluster at max (e.g. Azure Disk, Azure File, SMB and SecretStore) and the instances are small.
Gathering these objects is important because we already gather Deployment, DaemonSets and other objects of CSI drivers by generic must-gather, and ClusterCSIDriver objects complement those info with managementState, cipherSuites, and various condition statuses for each CSI driver.
> OCPBUGS-44264: Collect all clustercsidriver resources

- collection-scripts/gather
- collection-scripts/gather_machineconfig_ondisk
- collection-scripts/gather_machineconfigdaemon_termination_logs
- collection-scripts/gather_ppc
This PR gathers a few debug artifacts pertaining to the machine-config-daemon implemented by openshift/machine-config-operator#4723 and openshift/machine-config-operator#4731. It also gathers the MachineConfiguration object, which is an singleton operator level object used to configure the MCO.
> NO-ISSUE: gather additional MCO debug artifacts

- collection-scripts/gather_ppc
This adds the `MachineConfigNodes` and `PinnedImageSets` resources to must gathers.
**To test:**
1. Launch a 4.19 cluster with tech preview enabled.
```
launch 4.19.0-0.ci-2025-04-28-053740 aws,techpreview
```
2. Apply a PIS.
<details><summary>Example PIS</summary>
<pre>
apiVersion: machineconfiguration.openshift.io/v1
kind: PinnedImageSet
metadata:
name: test-pinned
labels:
machineconfiguration.openshift.io/role: "worker"
spec:
pinnedImages:
- name: quay.io/openshift-release-dev/ocp-release@sha256:513cf1028aa1a021fa73d0601427a0fbcf6d212b88aaf9d76d4e4841a061e44e
- name: quay.io/openshift-release-dev/ocp-release@sha256:61eae2d261e54d1b8a0e05f6b5326228b00468364563745eed88460af04f909b
</pre>
</details>
```
$ oc apply -f <pis-file>
```
3. Create the must-gather from the updated `gather_ppc` …
> MCO-1648: MCO-1649: Add `machineconfignodes` and `pinnedimagesets` to must-gather

- collection-scripts/gather_network_logs_basics
After IPsec is upgraded from 4.14 into later versions, API option for IPsec in networks.operator.openshift.io cluster object continues to have {} in the ipsecConfig and may not be migrated to newer version containing IPsec mode option. This is supported in OCP for backward compatibility, so mg needs fixing to collect IPsec data when API configured with old option.
> OCPBUGS-52367: Fix collecting IPsec data for upgrade

- collection-scripts/gather_network_logs_basics
The ClusterUserDefinedNetwork (CUDN) is cluster-scoped, installed by cluster-network-operator [1].
Creating CUDN CR result with a NetworkAttachmentDefinition (NAD) CR being created according to the CUDN CR 'spec.network', in each selected namespaces according to the CUDN CR 'spec.namespaceSelector'.
Collect CUDN CRs.
Having CUDN CRs collected enable troubleshooting OVN-Kubernetes user-defined networks in case of miss-configurations or env issues. The
[1] https://github.com/openshift/cluster-network-operator
> CORENET-5412: network: Gather OVN-Kubernetes CUDN CRs
